### ISSUE TITLE
Feature Request: Include only option

### ISSUE THREAD

**Issue by MACscr** [awcodes/filament-quick-create#11]
i have over 20 resources and new ones are added often. I would really love to only have in my quick create menu the 4-5 resources I actually want there versus having to exclude everything i dont want.

**Comment by FDT2k** [comment]
I would like an include feature  :+1: , and to avoid conflict, it could be like : 

```php
QuickCreate::getResourcesUsing(function():array{
    return [
        MyResource::class,
        MySecondRessource::class
    ];
}
```

and by default it would get All Resources
