### ISSUE TITLE
Feature Request: Simple Resource Support

### ISSUE THREAD

**Issue by MACscr** [awcodes/filament-quick-create#12]
Would love to be able to launch a modal for resources that do not have a dedicated EditRecord page.

**Comment by awcodes** [comment]
I've been giving this some thought for a while now but I'm not entirely sure how to accomplish it. I can't come up with a good way to automatically inspect the resource for the form and then inject it to an action while retaining all of the form's functionality.

**Comment by awcodes** [comment]
if you have any ideas, then I'm open to them.
