### ISSUE TITLE
option enabled without create page.

### ISSUE THREAD

**Issue by SkeyPunyapal** [awcodes/filament-quick-create#14]
is there any way to hide this option if users do not have rides to create any resources?

I mean it works fine if the user has 3 access from 6 resources it shows 3 of them but it isn't hiding when the user has 0  from 6 resources it shows a blank drop-down. 

it may be done by checking the item count in the blade component.

![image](https://user-images.githubusercontent.com/112473216/193520189-5915c7df-898d-4a5d-b772-9a70a49e52a2.png)

**Comment by awcodes** [comment]
This is fixed in v1.1.0

Thanks.
