### ISSUE TITLE
Adding resources to the exclude array doesn't do anything...

### ISSUE THREAD

**Issue by bartclaeys** [awcodes/filament-quick-create#16]
Is the config cached somehow?

**Comment by bartclaeys** [comment]
Cleared the config, the excluded resources still show up...

**Comment by bartclaeys** [comment]
Using fresh install of Laravel v9.36.4 using latest Filament version.

**Comment by awcodes** [comment]
You need to define the full namespace for the resource.

```php
\App\Filament\Resources\UserResource::class
```

I'll update the docs.

Thanks.
