### ISSUE TITLE
Overflow scroll on dropdown

### ISSUE THREAD

**Issue by alperenersoy** [awcodes/filament-quick-create#3]
![image](https://user-images.githubusercontent.com/83382417/180251882-2d61588b-cba4-4ea4-8039-947b1a6e0e6b.png)

Is overflow-scroll class in [this element](https://github.com/awcodes/filament-quick-create/blob/8bdfe40819366a121e038c0a73d896b7d215e5be/resources/views/components/create-menu.blade.php#L28) intentional? It has no impact before running `npm run dev` due to filament bundle doesn't have this class.

**Comment by awcodes** [comment]
Yes this is intentional to keep the menu from being too long. Image if you have 20 resources in your app. the menu would take up the height of the window.

**Comment by alperenersoy** [comment]
![image](https://user-images.githubusercontent.com/83382417/180263692-9c95eb7e-13d3-45a3-a439-294ee8ffba02.png)

Since it has max-height `overflow-y-auto` should also do the trick and looks better when doesn't have enough elements to scroll. I can PR that if you are ok with it. Great idea and great package btw!

**Comment by awcodes** [comment]
Feel free to PR. Thanks.
