### ISSUE TITLE
SPA + Tenancy gives wrong URLs 

### ISSUE THREAD

**Issue by wannesmatthys** [awcodes/filament-quick-create#49]
### Filament Version

v3

### Plugin Version

3.3.2

### PHP Version

8.2

### Problem description

When we enable SPA mode + multi tenancy and you switch your team, the items on the quick create action do not get resetted. So when you click on an item, it takes you back to the other tenant. (See video)

https://github.com/awcodes/filament-quick-create/assets/40867324/0ba25486-2f77-4ac0-87c5-df807d22639e

### Expected behavior

The URLs on the navigation should get refreshed upon team change and it should link to correct team.

### Steps to reproduce

1. Enable SPA
2. Add multiple teams
3. Switch from team
4. Use quick create -> you'll be redirected to the wrong team

**Comment by awcodes** [comment]
Until SPA mode is more stable in livewire itself I'm not totally interested in worrying about support for it. However, I would accept a PR if you can make it work.
